project:
  type: website
  post-render:
    - make_pdf.R

website:
  title: "Tim Sippel's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: CV
        menu:
          - href: CV.qmd
            text: CV
          - href: CV/Projects.qmd
            text: Projects
          - href: CV/Publications.qmd
            text: Publications


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



