# Shared publication parsing/formatting for CV.qmd and Publications.qmd.
#
# Publications come from Bibliography/cv_publications.bib, generated by
# sync_zotero.R directly from the local Zotero database. Entries tagged
# "cv-selected" in Zotero carry `keywords = {selected}` and are surfaced under
# "Selected Publications" on the CV. Requires stringr (loaded via tidyverse).

parse_publications <- function(bib_path, author_surname = "Sippel") {
  raw <- readLines(bib_path, warn = FALSE, encoding = "UTF-8")
  starts <- grep("^@", raw)
  ends <- c(starts[-1] - 1, length(raw))
  entries <- mapply(function(s, e) paste(raw[s:e], collapse = "\n"),
                    starts, ends, SIMPLIFY = TRUE)

  get_field <- function(entry, name) {
    m <- str_locate(entry, regex(paste0("\\n\\s*", name, "\\s*=\\s*"), ignore_case = TRUE))
    if (is.na(m[1, 1])) return(NA_character_)
    s <- sub("^\\s+", "", substr(entry, m[1, 2] + 1, nchar(entry)))
    first <- substr(s, 1, 1)
    if (first == "{") {
      depth <- 0L; out <- ""
      for (ch in strsplit(s, "")[[1]]) {
        if (ch == "{") depth <- depth + 1L else if (ch == "}") depth <- depth - 1L
        if (depth == 0L && ch == "}") break
        if (!(ch == "{" && depth == 1L)) out <- paste0(out, ch)
      }
      return(str_trim(out))
    }
    if (first == "\"") {
      j <- str_locate(substr(s, 2, nchar(s)), "\"")[1, 1]
      return(str_trim(substr(s, 2, j)))
    }
    str_trim(sub(",.*$", "", strsplit(s, "\n")[[1]][1]))
  }

  delatex <- function(x) {
    accents <- list(
      c("\\\\c\\s*\\{?c\\}?", "ç"), c("\\\\c\\s*\\{?C\\}?", "Ç"),
      c("\\\\'\\{?a\\}?", "á"), c("\\\\'\\{?e\\}?", "é"), c("\\\\'\\{?i\\}?", "í"),
      c("\\\\'\\{?o\\}?", "ó"), c("\\\\'\\{?u\\}?", "ú"), c("\\\\'\\{?n\\}?", "ń"),
      c("\\\\`\\{?a\\}?", "à"), c("\\\\`\\{?e\\}?", "è"),
      c("\\\\\"\\{?a\\}?", "ä"), c("\\\\\"\\{?o\\}?", "ö"), c("\\\\\"\\{?u\\}?", "ü"),
      c("\\\\~\\{?n\\}?", "ñ"), c("\\\\~\\{?a\\}?", "ã"),
      c("\\\\\\^\\{?o\\}?", "ô"), c("\\\\\\^\\{?e\\}?", "ê")
    )
    for (a in accents) x <- gsub(a[1], a[2], x)
    x
  }

  clean <- function(x) {
    if (is.na(x)) return(x)
    x <- delatex(x)
    x <- gsub("[{}]", "", x)
    x <- gsub("\\\\&", "&", x)
    x <- gsub("--", "–", x)
    x <- str_squish(x)
    if (x %in% c("-", "–", "")) return(NA_character_)
    x
  }

  is_selected <- function(e) {
    kw <- get_field(e, "keywords")
    !is.na(kw) && str_detect(kw, regex("selected", ignore_case = TRUE))
  }

  # Anonymous / institution-authored reports the user contributed to but is not
  # personally credited on. Matched either by their institutional author string,
  # or (for author-less reports) by a distinctive phrase in the title.
  anon_authors <- c("National Academies of Sciences", "Informal Offshore Wind Energy Group")
  anon_titles  <- c("National Assessment by the Nature Record")

  recs <- lapply(entries, function(e) {
    typ <- tolower(sub("^@(\\w+).*", "\\1", e))
    au <- get_field(e, "author")
    au_c <- clean(au)
    yr <- get_field(e, "year")
    # Require a complete year; drop undated items (Zotero placeholder "0000")
    if (is.na(yr) || !str_detect(yr, "^\\s*\\d{4}\\s*$") || as.integer(str_trim(yr)) == 0)
      return(NULL)

    sel <- is_selected(e)
    title_c <- clean(get_field(e, "title"))
    anon_by_author <- !is.na(au_c) && any(str_detect(au_c, regex(anon_authors, ignore_case = TRUE)))
    anon_by_title  <- !is.na(title_c) && any(str_detect(title_c, regex(anon_titles, ignore_case = TRUE)))
    if (anon_by_author || anon_by_title) {
      pub <- clean(get_field(e, "publisher"))
      if (is.na(pub)) pub <- clean(get_field(e, "institution"))
      if (!is.na(au_c)) {
        disp <- au_c
        nas <- str_extract(au_c, regex("National Academies of Sciences.*?Medicine", ignore_case = TRUE))
        if (!is.na(nas)) disp <- nas
      } else {
        disp <- pub   # author-less report: credit the publishing organization
      }
      # Don't repeat the publisher when it is the same as the author credit
      pub_show <- if (!is.na(pub) && !identical(pub, disp)) pub else NA_character_
      return(list(year = as.integer(str_trim(yr)), institutional = TRUE, author = disp,
                  title = title_c, publisher = pub_show, selected = sel))
    }

    if (is.na(au) || !str_detect(tolower(au), tolower(author_surname))) return(NULL)
    if (!typ %in% c("article", "incollection", "techreport")) return(NULL)
    venue <- get_field(e, "journal")
    if (is.na(venue)) venue <- get_field(e, "booktitle")
    if (is.na(venue)) venue <- get_field(e, "institution")
    venue_c <- clean(venue)
    if (!is.na(venue_c) && str_detect(venue_c, regex("Fishing News|Magazine", ignore_case = TRUE)))
      return(NULL)
    list(year = as.integer(str_trim(yr)), institutional = FALSE, type = typ, author = clean(au),
         title = clean(get_field(e, "title")), venue = venue_c,
         volume = clean(get_field(e, "volume")), number = clean(get_field(e, "number")),
         selected = sel, pages = clean(get_field(e, "pages")))
  })
  recs <- Filter(Negate(is.null), recs)

  norm <- vapply(recs, function(r) substr(gsub("[^a-z0-9]", "", tolower(r$title)), 1, 55), "")
  recs <- recs[!duplicated(norm)]
  ord <- order(-vapply(recs, `[[`, integer(1), "year"),
               vapply(recs, `[[`, character(1), "title"))
  recs[ord]
}

# Reduce a single author to "Last, F." (handles "Last, First M." and "First Last")
to_last_initial <- function(name) {
  name <- str_trim(name)
  if (str_detect(name, ",")) {
    last <- str_trim(sub(",.*$", "", name))
    rest <- str_trim(sub("^[^,]*,", "", name))
  } else {
    toks <- str_split(name, "\\s+")[[1]]
    if (length(toks) == 1) return(name)
    last <- toks[length(toks)]
    rest <- toks[1]
  }
  init <- str_extract(rest, "[A-Za-z]")
  if (is.na(init)) return(last)
  paste0(last, ", ", init, ".")
}

# Names as "Last, F."; for >3 authors show the first two plus Sippel, others "…"
format_authors <- function(author, surname = "Sippel") {
  parts <- str_split(author, "\\s+and\\s+")[[1]]
  norm <- unname(vapply(str_trim(parts), to_last_initial, ""))
  is_me <- str_detect(norm, regex(paste0("^", surname), ignore_case = TRUE))
  disp <- ifelse(is_me, paste0("**", norm, "**"), norm)
  n <- length(norm)
  if (n <= 3) {
    if (n == 1) return(disp[1])
    if (n == 2) return(paste0(disp[1], " & ", disp[2]))
    return(paste0(disp[1], ", ", disp[2], " & ", disp[3]))
  }
  me_idx <- which(is_me)[1]
  if (!is.na(me_idx) && me_idx > 2) {
    paste0(disp[1], ", ", disp[2], ", … ", disp[me_idx])
  } else {
    paste0(disp[1], ", ", disp[2], ", …")
  }
}

# Classify a parsed record for grouping: reports vs. peer-reviewed (journal
# articles and book chapters). Reports are technical reports, institution-
# authored reports, or "journal articles" whose venue is really an agency /
# report series (some are mis-typed as articles in Zotero).
is_report <- function(r) {
  if (isTRUE(r$institutional) || identical(r$type, "techreport")) return(TRUE)
  v <- r$venue
  if (is.na(v)) return(TRUE)   # working papers / reports have no journal venue
  report_venue <- regex(paste(c(
    "Report", "Ministry", "NOAA", "Commission", "Working Paper",
    "Technical Memorandum", "Consensus", "Assessment", "Scientific Committee",
    "Fisheries Science Center"
  ), collapse = "|"), ignore_case = TRUE)
  str_detect(v, report_venue)
}

format_entry <- function(r) {
  if (isTRUE(r$institutional)) {
    out <- paste0(r$author, " (", r$year, "). *", r$title, "*.")
    if (!is.na(r$publisher) && nzchar(r$publisher)) out <- paste0(out, " ", r$publisher, ".")
    return(out)
  }
  out <- paste0(format_authors(r$author), " (", r$year, "). ", r$title)
  if (!grepl("[.?!]$", out)) out <- paste0(out, ".")
  if (!is.na(r$venue) && nzchar(r$venue)) {
    out <- paste0(out, " *", r$venue, "*")
    if (!is.na(r$volume) && nzchar(r$volume)) out <- paste0(out, " ", r$volume)
    if (!is.na(r$pages) && nzchar(r$pages)) out <- paste0(out, ": ", r$pages)
    out <- paste0(out, ".")
  } else if (!is.na(r$number) && nzchar(r$number)) {
    out <- paste0(out, " ", r$number, ".")
  }
  out
}
